version: "3"
services:
  go_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Akash@123
    networks:
      - mynetwork
  
  frontend:
    image: frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - go_backend

networks:
  mynetwork:
    driver: bridge
